USE [master]
GO

/****** Object:  Database [SqlDependency_TDB]    Script Date: 2018/1/4 下午 04:32:37 ******/
CREATE DATABASE [SqlDependency_TDB]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'SqlDependency_TDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SqlDependency_TDB.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON
( NAME = N'SqlDependency_TDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SqlDependency_TDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SqlDependency_TDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SqlDependency_TDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SqlDependency_TDB] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET ANSI_NULLS OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET ANSI_PADDING OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET ARITHABORT OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [SqlDependency_TDB] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [SqlDependency_TDB] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET  ENABLE_BROKER
GO

ALTER DATABASE [SqlDependency_TDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [SqlDependency_TDB] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET RECOVERY SIMPLE
GO

ALTER DATABASE [SqlDependency_TDB] SET  MULTI_USER
GO

ALTER DATABASE [SqlDependency_TDB] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [SqlDependency_TDB] SET DB_CHAINING OFF
GO

ALTER DATABASE [SqlDependency_TDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [SqlDependency_TDB] SET TARGET_RECOVERY_TIME = 0 SECONDS
GO

ALTER DATABASE [SqlDependency_TDB] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [SqlDependency_TDB] SET  READ_WRITE
GO


